os:
  - linux
  - osx
language: csharp
solution: Substructio.sln
install:
  - .paket/paket.bootstrapper.exe
  - .paket/paket.exe restore
notifications:
  email:
    on_success: change
    on_failure: always
    on_start: never