version: 1.0.{build}-appveyor
image: Visual Studio 2015
configuration:
- Debug
- Release
before_build:
  - cmd: .paket\paket.bootstrapper.exe
  - cmd: .paket\paket.exe restore
build:
  project: Substructio.sln
  parallel: true
  verbosity: minimal